### ISSUE TITLE
Update results for Pillow-SIMD 4.3

### ISSUE THREAD

**Issue by homm** [jcupitt/vips-bench#6]
Hi!

Pillow-SIMD 4.3.0 with significant performance improvements is out. Some of improvements are releted to this benchamark.

I modified the test script a bit just to make clear what is happening.

<details>
 <summary>Full test script</summary>

```python
#!/usr/bin/env python
from __future__ import print_function

import sys
from PIL import Image, ImageFilter, PILLOW_VERSION
import time

class Timer:
    def __init__(self, name):
        self.name = name

    def __enter__(self):
        self.start = time.time()
        self.cpu = time.clock()
        return self

    def __exit__(self, *args):
        print('>>>', self.name, time.time() - self.start)


# just to confirm we are getting the right version
print("pillow.py: PILLOW_VERSION =", PILLOW_VERSION)

def run():
    with Timer('open'):
        im = Image.open(sys.argv[1])
        im.load()

    with Timer('crop'):
        # Crop 100 pixels off all edges.
        im = im.crop((100, 100, im.size[0] - 100, im.size[1] - 100))

    with Timer('resize'):
        # Shrink by 10%
        im = im.resize((int(im.width * 0.9), int(im.height * 0.9)), Image.NEAREST)

    with Timer('apply filter'):
        # sharpen
        filter = ImageFilter.Kernel((3, 3),
                  (-1, -1, -1,
                   -1, 16, -1,
                   -1, -1, -1))
        im = im.filter(filter)

    with Timer('save'):
        # write back again
        # im.save(sys.argv[2], format='tiff')
        # I don't have pc with SSD for tests, write to memory
        im.tobytes()


with Timer('sum'):
    run()
```
</details>

The difference on my pc (only for example, of course):

```bash
$ pip install pillow-simd==4.2.1.post0
Successfully installed pillow-simd-4.2.1.post0

$ time ./pillow.py ./vips.tiff
pillow.py: PILLOW_VERSION = 4.2.1.post0
>>> open 0.106125116348
>>> crop 0.0340759754181
>>> resize 0.027755022049
>>> apply filter 0.59959602356
>>> save 0.0295100212097
>>> sum 0.803848028183

real	0m0.819s
user	0m0.748s
sys	0m0.068s
```

```bash
$ pip install pillow-simd==4.3.0.post0
Successfully installed pillow-simd-4.3.0.post0

$ time ./pillow.py ./vips.tiff 
pillow.py: PILLOW_VERSION = 4.3.0.post0
>>> open 0.0663890838623
>>> crop 0.0178101062775
>>> resize 0.0208790302277
>>> apply filter 0.0534710884094
>>> save 0.0313007831573
>>> sum 0.190583229065

real	0m0.223s
user	0m0.176s
sys	0m0.044s
```

## Aggressive optimizations

Just for example of maximum performance. There are three tweaks and each of them can be used separately:

1. Avoid cropping and resize with box
2. Compile with AVX2
3. Use [Pillow's memory pool](https://pillow.readthedocs.io/en/4.3.x/reference/block_allocator.html#memory-pools) and custom allocator

Difference in `pillow_box_crop.py` is:

```python
    with Timer('crop'):
        # Crop 100 pixels off all edges.
        box = (100, 100, im.width - 100, im.height - 100)
        width, height = (im.width - 200, im.height - 200)

    with Timer('resize'):
        # Shrink by 10%
        im = im.resize((int(width * 0.9), int(height * 0.9)), Image.NEAREST, box=box)
```

```bash 
# install and recompile with avx2
$ CFLAGS="-mavx2" pip install pillow-simd==4.3.0.post0 --no-cache-dir

# use custom memory allocator and tune memory settings
$ time LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1 PILLOW_BLOCK_SIZE=4m PILLOW_BLOCKS_MAX=64 ./pillow_box_crop.py ./vips.tiff
pillow.py: PILLOW_VERSION = 4.3.0.post0
>>> open 0.0655601024628
>>> crop 7.15255737305e-06
>>> resize 0.0184090137482
>>> apply filter 0.035365819931
>>> save 0.0275781154633
>>> sum 0.147360086441

real	0m0.182s
user	0m0.124s
sys	0m0.052s
```

**Comment by jcupitt** [comment]
Hello @homm! That's a very impressive speedup. I'll patch the benchmark and rerun on the test machine later today.

**Comment by homm** [comment]
Thanks!
I'm not sure that is it fair to patch the script, because the box argument is not an obvious way to work with API. As I understand, there are no such hacks for other libraries in the test.

It's more the question to you: what kind of benchmark you want. If you want benchmarks games like http://benchmarksgame.alioth.debian.org/, then you probably should include the fix. If you want just to compare libraries in similar conditions, you probably shoulsdn't.

**Comment by jcupitt** [comment]
The ImageMagick one uses shave, which combines load + crop, but you're right, I don't think anyone else is combing crop + resize. You can pass a crop to the libvips resizer, for example, but it's not being used.

The benchmark has more serious problems really. The big one is that it's now more than 10 years old and modern machines (and libraries) are just too quick for it. 

It's also just not a very good test of libvips: if you try in cachegrind you'll see almost 70% of CPU time is being spent in two lines of C in the bilinear interpolator, ouch.

**Comment by jcupitt** [comment]
Hello again, I'm seeing a strange problem in pillow-simd:

```
john@mm-jcupitt5 ~/GIT/vips-bench (master) $ ./pillow.py tmp/x.tif tmp/x2.tif
pillow.py: PILLOW_VERSION = 4.0.0
john@mm-jcupitt5 ~/GIT/vips-bench (master) $ pip install --user pillow-simd
Collecting pillow-simd
Requirement already satisfied: olefile in /home/john/.local/lib/python2.7/site-packages (from pillow-simd)
Installing collected packages: pillow-simd
Successfully installed pillow-simd-4.3.0.post0
john@mm-jcupitt5 ~/GIT/vips-bench (master) $ ./pillow.py tmp/x.tif tmp/x2.tif
pillow.py: PILLOW_VERSION = 4.3.0.post0
Traceback (most recent call last):
  File "./pillow.py", line 12, in <module>
    im = im.crop((100, 100, im.width - 100, im.height - 100))
  File "/home/john/.local/lib/python2.7/site-packages/PIL/Image.py", line 1073, in crop
    self.load()
  File "/home/john/.local/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 1053, in load
    return super(TiffImageFile, self).load()
  File "/home/john/.local/lib/python2.7/site-packages/PIL/ImageFile.py", line 206, in load
    decoder.setimage(self.im, extents)
ValueError: tile cannot extend outside image
```

Is it stricter about tiff file sanity now? Though I think it's OK to have cropped tiles, as far as I know.

**Comment by jcupitt** [comment]
I swapped it to strip tiff instead and on the test machine I now see:

```
$ ./benchmark.sh 
clearing test area ...
building test image ...
tmp/x.tif: 5000x5000 uchar, 3 bands, srgb, tiffload
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
program, time (s), peak memory (MB)
tiffcp, 0.19, 147.95703125
vips-c, 0.16, 41.1640625
pillow.py: PILLOW_VERSION = 4.3.0.post0
pillow, 0.33, 141.12890625
strip-vips-c, 0.21, 61.43359375
ppm-vips-c, 0.16, 35.0859375
pyvips2.py, 0.34, 51.73828125
vips.lua, 0.17, 41.90234375
```

A very impressive jump in performance! Shall I update the page, or would you like to look into the strange tiff error?

**Comment by homm** [comment]
I'd like to look into the tiff error first. Could you share the test image?

**Comment by jcupitt** [comment]
It's just the one made by the benchmark script, so:

```
vips colourspace sample2.v $tmp/t1.v srgb
vips replicate $tmp/t1.v $tmp/t2.v 20 15
vips extract_area $tmp/t2.v $tmp/x.tif[tile] 0 0 5000 5000
```

As far as I know, just a vanilla uncompressed tiled RGB tiff.

**Comment by homm** [comment]
Indeed, something was changed in 4.0..4.1. And even `ImageFile.LOAD_TRUNCATED_IMAGES` doesn't help here.

> Though I think it's OK to have cropped tiles, as far as I know.

Yes, this should be fixed on the Pillow side. Surprisingly, I haven't met that kind of files in the wild.

Anyway, I think this is a good idea to use striped tiff for all libraries, not only for Pillow.

**Comment by jcupitt** [comment]
You're right. I'll update the timings tomorrow, I have to head home now.

**Comment by homm** [comment]
Sure, no problem. Thanks in advance.

**Comment by homm** [comment]
I took a look at Pillow 4.0 result with sticking tiles and saw that tiles at right and bottom borders are actually cropped and there is a black color several pixels width. So it didn't work from the start.

**Comment by homm** [comment]
Sorry for bothering, do you have an update about his?

**Comment by jcupitt** [comment]
Sorry, I've been side-tracked. Maybe tomorrow.

**Comment by jcupitt** [comment]
I've done some updating, but not all. More tomorrow!

**Comment by jcupitt** [comment]
OK, pushed some changes: 

- it's all adaptive everywhere now I think
- pillow is using BILINEAR
- no more tiled tiffs, they are all strip now
- vips is using sequential mode everywhere

I'll update the table too.

**Comment by jcupitt** [comment]
OK, table updated as well. Phew!

**Comment by homm** [comment]
Thank you!
